name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release_id: ${{ steps.create-release.outputs.release_id }}
    steps:
      - id: create-release
        run: |
          curl --silent --show-error --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "${{ github.ref_name }}",
              "draft": true,
              "generate_release_notes": true
            }' \
            | tee output.json
          echo "release_id=$(cat output.json | jq -r '.id')" >> $GITHUB_OUTPUT
  build-linux-amd64:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: build-tools/build-linux-amd64.sh
      - run: |
          curl --silent --show-error --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release.outputs.release_id }}/assets?name=polones-desktop-linux-amd64" \
            --data-binary "@target/x86_64-unknown-linux-gnu/release/polones-desktop"
  build-linux-arm64:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: docker run --privileged --rm tonistiigi/binfmt --install linux/arm64
      - run: build-tools/build-linux-arm64.sh
      - run: |
          curl --silent --show-error --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release.outputs.release_id }}/assets?name=polones-desktop-linux-arm64" \
            --data-binary "@target/aarch64-unknown-linux-gnu/release/polones-desktop"
  build-linux-armv7:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: docker run --privileged --rm tonistiigi/binfmt --install linux/arm/v7
      - run: build-tools/build-linux-armv7.sh
      - run: |
          curl --silent --show-error --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release.outputs.release_id }}/assets?name=polones-desktop-linux-armv7" \
            --data-binary "@target/armv7-unknown-linux-gnueabihf/release/polones-desktop"
  build-windows-amd64:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: build-tools/build-windows-amd64.sh
      - run: |
          curl --silent --show-error --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release.outputs.release_id }}/assets?name=polones-desktop-windows-amd64.exe" \
            --data-binary "@target/x86_64-pc-windows-gnu/release/polones-desktop.exe"
