name: Release
on:
  push:
    tags: ["v[0-9]+\\.[0-9]+\\.[0-9]+*"]
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release_id: ${{ steps.create-release.outputs.release_id }}
    steps:
      - id: create-release
        run: |
          curl --silent --show-error --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "${{ github.ref_name }}",
              "draft": true,
              "generate_release_notes": true
            }' \
            | tee output.json
          echo "release_id=$(cat output.json | jq -r '.id')" >> $GITHUB_OUTPUT
  build-linux-amd64:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir build build/sdl-config build/sdl-build
          git clone https://github.com/libsdl-org/SDL.git --branch release-2.30.10 --depth 1 build/sdl-source
          docker build --build-arg USER=$(id -u) --build-arg GROUP=$(id -g) -f ./build-tools/build-sdl-linux-amd64.Dockerfile -t build-sdl-linux-amd64:latest ./build-tools
          docker run -v ./build/sdl-source:/sdl-source -v ./build/sdl-config:/sdl-config -v ./build/sdl-build:/sdl-build build-sdl-linux-amd64:latest
          docker build --build-arg USER=$(id -u) --build-arg GROUP=$(id -g) -f ./build-tools/build-linux-amd64.Dockerfile -t build-linux-amd64:latest ./build-tools
          docker run -v ./build/sdl-build:/sdl-build -v ./:/polones build-linux-amd64:latest
          curl --silent --show-error --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release.outputs.release_id }}/assets?name=polones-desktop-linux-amd64" \
            --data-binary "@target/release/polones-desktop"
